name: Update Image

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  update-image-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pillow

      - name: Generate new image
        run: python src/main.py

      - name: Commit updated image
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add image.jpg
          git commit -m 'Update image'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
